services:
    nginx:
       image: dockerenthusiast1992/nginx:5
       deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == manager]
       env_file: ../environments/common.env
       volumes:
         - nginx-logs-volume:/var/log/nginx/
  
    express-gateway-service:
      image: dockerenthusiast1992/my-express-gateway:5
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == manager]
      env_file: ../environments/common.env
      volumes:
         - express-logs-volume:/var/log/express-gateway/

    filebeat:
      image: dockerenthusiast1992/filebeat:5
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == manager]
      environment:
         - strict.perms=false
      volumes:
         - nginx-logs-volume:/var/log/nginx/:ro
         - express-logs-volume:/var/log/express-gateway/:ro


volumes:
  mongo-data:
  nginx-logs-volume:
  express-logs-volume:

networks:
   shared-swarm-net-dev:
      external: true
   shared-swarm-net-prod:
      external: true

  # In this example, mongo-data is a named volume that ensures all data written 
  # by the MongoDB container to /data/db (MongoDB's default data directory) is saved persistently 
  # on the host system, even if the mongodb container is removed or recreated.